language: node_js
git:
  depth: 10
branches:
  only:
    - master
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
before_install:
  - npm install -g grunt
  - npm install -g grunt-cli